### ISSUE TITLE
Share "is connected" to all contacts

### ISSUE THREAD

**Issue by adonese** [tutipay/ws#21]
We have a map of connected clients and we also have a way to know when a client disconnects (we need to test this part thu, `<- unregister`). It is good to broadcast the live status of chat members to their friends, so that they know X is connected at the moment

**Comment by mseltahir** [comment]
To do this I think we first need to introduce the concept of "contacts" to our database. I was thinking maybe we add another table and each row should represent a relationship (e.g. X is a contact of Y, X is a contact of Z) and so on.
Do you have a better way in mind @adonese ?

**Comment by adonese** [comment]
Not really, let's go with yours
